name: Release

on:
  push:
    tags:
      - 'v*'
      - 'rc-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: make docker

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ startsWith(github.ref_name, 'rc-') && 'PRE' || 'REL' }}: ${{ github.ref_name }}"
          files: |
            build/out/BurnOS.iso
            build/bin/kerneldbg.bin
            build/bin/kernelstd.bin
          generate_release_notes: true
          prerelease: ${{ startsWith(github.ref_name, 'rc-') }}
          make_latest: ${{ !startsWith(github.ref_name, 'rc-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
